name: assist_health
description: A new Flutter project.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: '>=3.0.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  http: ^1.2.0
  firebase_core: ^2.17.0
  firebase_auth: ^4.10.1
  firebase_storage: ^11.3.1
  cloud_firestore: ^4.11.0
  bloc: ^8.1.3
  country_picker: ^2.0.21
  image_picker: ^1.0.4
  pinput: ^3.0.1
  uuid: ^4.0.0
  timeline_tile: ^2.0.0
  file_picker: ^6.1.1
  path_provider: ^2.0.5
  open_file: ^3.3.2
  date_picker_timeline: ^1.2.5
  intl: ^0.18.1
  flutter_staggered_animations: ^1.1.1
  multi_image_picker: ^4.8.1
  carousel_slider: ^4.2.1
  dots_indicator: ^3.0.0
  multi_select_flutter: ^4.1.3
  flutter_styled_toast: ^2.2.1
  url_launcher: ^6.2.2
  flutter_rating_bar: ^4.0.1
  agora_rtc_engine: ^5.0.0
  permission_handler: ^11.0.1
  flutter_local_notifications: ^16.2.0
  timezone: ^0.9.2
  flutter_timezone: ^1.0.7
  table_calendar: ^3.0.9
  cupertino_icons: ^1.0.2
  font_awesome_flutter: ^10.6.0
  fl_chart: ^0.65.0
  equatable: ^2.0.5
  flutter_bloc: ^8.1.4
  chat_bubbles: ^1.5.0
  flutter_dotenv: ^5.1.0
  syncfusion_flutter_sliders: ^25.1.37
  flutter_xlider: ^3.5.0
  shared_preferences: ^2.2.2
  translator: ^1.0.0
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.

flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
     - assets/doctor1.jpg
     - assets/doctor2.jpg
     - assets/doctor3.jpg
     - assets/doctor4.jpg
     - assets/doctors.png
     - assets/slider1.jpg
     - assets/slider2.jpg
     - assets/slider3.jpeg
     - assets/empty-box.png
     - assets/lined heart.png
     - assets/sample_image.png
     - assets/sample_image.jpeg
     - assets/guidanceVietQR.png
     - assets/health_care_logo.jpg
     - assets/health_care_logo_nobg.png
     - assets/no_result_search_icon.png
     - assets/enter_medical_record.jpg
     - assets/image.png
     - assets/doctor_ai.png
     - assets/recommendation_get_started.png
     - assets/.evn

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages
