name: assist_health
description: A new Flutter project.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=3.0.6 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  http: ^1.2.0
  firebase_core: ^3.10.0
  firebase_auth: ^5.4.0
  firebase_storage: ^12.4.0
  cloud_firestore: ^5.6.1
  firebase_app_check: ^0.3.2
  bloc: ^8.1.3
  country_picker: ^2.0.21
  image_picker: ^1.0.4
  pinput: ^3.0.1
  uuid: ^4.0.0
  timeline_tile: ^2.0.0
  file_picker: ^6.1.1
  path_provider: ^2.0.5
  open_file: ^3.3.2
  date_picker_timeline: ^1.2.5
  intl: ^0.19.0
  flutter_staggered_animations: ^1.1.1
  dots_indicator: ^3.0.0
  multi_select_flutter: ^4.1.3
  flutter_styled_toast: ^2.2.1
  url_launcher: ^6.2.2
  flutter_rating_bar: ^4.0.1
  agora_rtc_engine: ^5.0.0
  permission_handler: ^11.0.1
  timezone: ^0.9.2
  table_calendar: ^3.0.9
  cupertino_icons: ^1.0.2
  font_awesome_flutter: ^10.6.0
  fl_chart: ^0.65.0
  equatable: ^2.0.5
  flutter_bloc: ^8.1.4
  chat_bubbles: ^1.5.0
  flutter_dotenv: ^5.1.0
  syncfusion_flutter_sliders: ^25.1.37
  flutter_xlider: ^3.5.0
  shared_preferences: ^2.2.2
  translator: ^1.0.0
  cached_network_image: ^3.3.1
  google_generative_ai: ^0.4.3
  percent_indicator: ^4.2.3
  flutter_screenutil: ^5.9.3
  carousel_slider: ^5.0.0
  win32: ^5.8.0
  youtube_player_flutter: ^8.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.

flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/doctor1.jpg
    - assets/doctor2.jpg
    - assets/doctor3.jpg
    - assets/doctor4.jpg
    - assets/doctors.png
    - assets/slider1.jpg
    - assets/slider2.jpg
    - assets/slider3.jpeg
    - assets/empty-box.png
    - assets/lined heart.png
    - assets/sample_image.png
    - assets/sample_image.jpeg
    - assets/guidanceVietQR.png
    - assets/health_care_logo.jpg
    - assets/health_care_logo_nobg.png
    - assets/no_result_search_icon.png
    - assets/image.png
    - assets/doctor_ai.png
    - assets/.evn
    - assets/vnpay_logo.png
    - assets/ship_cod_logo.png
    - assets/momo_logo.png
    - assets/empty-cart.png
    - assets/empty-location.png
    - assets/empty-order.png
    - assets/coupon.png
    - assets/bill.png
    - assets/payment_online.png
    - assets/recommendation/get_started.png
    - assets/recommendation/medical_record.png
    - assets/recommendation/doctor_3D.png
    - assets/recommendation/bg_gradient.png
    - assets/recommendation/bg_gradient1.png
    - assets/recommendation/avt_test.png
    - assets/recommendation/tip_sleep.png
    - assets/recommendation/tip_healthy_food.png
    - assets/recommendation/tip_exercise.png
    - assets/recommendation/tip_water.png
    - assets/describe_food.jpg
    - assets/glass.png
    - assets/empty_glass.png
    - assets/plank.gif
    - assets/planking.gif
    - assets/airbike.gif
    - assets/side-plank.gif
    - assets/dead_fish.gif
    - assets/crunch.gif
    - assets/big_cats.gif
    - assets/full_twist.gif
    - assets/leg_raise.gif
    - assets/crunch_scissor.gif
    - assets/power_boat.gif
    - assets/raise_bike.gif
    - assets/prone_knee.gif
    - assets/pushup_1.gif
    - assets/pushup_2.gif
    - assets/dumbbell_press.gif
    - assets/deck_fly.gif
    - assets/pull_over.gif
    - assets/barbell_bench.gif
    - assets/dumbbell.gif
    - assets/cable_fly.gif
    - assets/DBCurl.gif
    - assets/diamond_push.gif
    - assets/hammercurl.gif
    - assets/seatcurl.gif
    - assets/benchdip.gif
    - assets/dip.gif
    - assets/tricep_rope_pulldown.gif
    - assets/dumbelllie.gif
    - assets/cable_curl.gif
    - assets/stride_tubing.gif
    - assets/kickback.gif
    - assets/bd_squat.gif
    - assets/calf_band.gif
    - assets/lunge.gif
    - assets/split_squat.gif
    - assets/adductor.gif
    - assets/stationary.gif
    - assets/hip.gif
    - assets/sumo.gif
    - assets/kneeling.gif
    - assets/squat.gif
    - assets/leg_press.gif
    - assets/calf_raise.gif
    - assets/abs1.jpg
    - assets/abs2.jpg
    - assets/abs3.jpg
    - assets/chest1.jpg
    - assets/chest2.jpg
    - assets/chest3.jpg
    - assets/arm1.jpg
    - assets/arm2.jpg
    - assets/arm3.jpg
    - assets/leg1.jpg
    - assets/leg2.jpg
    - assets/leg3.jpg
    - assets/chatbot.png
    - assets/camera.png
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages
